name: Hello Universe
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jymartineau/github-octokit@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
